version: 2.1
orbs:
  node: circleci/node@4.7
jobs:
  build:
    docker:
      - image: cimg/node:16.10

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - node/install-packages:
          pkg-manager: npm

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

  test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout

      - run:
          name: Run tests
          command: npm test
      - run:
          name: Run static analysis
          command: npm run lint

workflows:
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
